# Generated by Django 5.0.14 on 2026-03-24 00:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenix', '0002_teaminvitation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('session_data', models.TextField()),
                ('repo', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField()),
                ('report_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fenix.user')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='fenix.session')),
            ],
            options={
                'db_table': 'fenix_session_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['session', '-version_number'], name='fenix_sessi_session_bb834c_idx')],
                'unique_together': {('session', 'version_number')},
            },
        ),
    ]
